import assert from "assert";
import { ResourceDetailsTreeItem } from "../../../views/resourceDetailsView/viewProvider";

/**
 * Asserts that the actual resource details tree items match the expected ones.
 * 
 * @param actualFields The ResourceDetailsTreeItems that were generated by the code.
 * @param expectedFields The expected fields, in order.
 */
export function assertExpectedResourceDetailsTreeItems(
  actualFields: ResourceDetailsTreeItem[],
  expectedFields: { name: string; value: string }[]
) {
  assert.strictEqual(actualFields.length, expectedFields.length, 'Number of fields does not match');
  for (let i = 0; i < expectedFields.length; i++) {
    assert.strictEqual(actualFields[i].label, expectedFields[i].name + ': ', `Label at index ${i} does not match`);
    assert.strictEqual(actualFields[i].description, expectedFields[i].value, `Description at index ${i} does not match`);
  }
}
